version: '3.8'
services:
  subscriber:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      isDocker: true
      CATEGORY_URL: "http://localhost:8082/categories/preferences?category-name="
      SENDINBLUE_API_KEY: "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"
    networks:
      default
    ports:
      - "5000:5000"
      -
networks:
  dsbd_prj_default:
    external: true

