# docker-compose.yml

version: '3'

services:

  db_customer:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dsbd_customer
    ports:
      - "3306:3306"

  db_category:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dsbd_category
    ports:
      - 3307:3306
  
  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    command: 'python main.py'
    depends_on:
      - db_customer
    environment:
      isDocker: true
      MYSQL_HOST: db_customer
      MYSQL_DATABASE: 'dsbd_customer'
      MYSQL_ROOT_PASSWORD: 'root'
      AUTH_URL: http://authentication:5002/authenticate
    networks:
      - default
    ports:
      - "5000:5000"

  category:
    build:
      context: ./category
      dockerfile: Dockerfile
    command: 'python main.py'
    depends_on:
      - db_category
    environment:
      isDocker: true
      MYSQL_HOST: db_category
      MYSQL_DATABASE: 'dsbd_category'
      MYSQL_ROOT_PASSWORD: 'root'
      AUTH_URL: http://authentication:5002/verify_token
    networks:
      - default
    ports:
      - "8082:8082"

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      isDocker: true
    networks:
      - default
    ports:
      - "5002:5002"

  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    command: 'python main.py'
    depends_on:
      - customer
      - category
    environment:
      isDocker: true
      CUSTOMER_URL: http://customer:5000/customers
      CATEGORY_URL: http://category:8082/categories
    networks:
      - default
    ports:
      - "8090:8090"

networks:
  default:
    name: dsbd_prj_default
    external: true
