# docker-compose.yml

version: '3'

services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dsbd_customer
    ports:
      - "3306:3306"
  
  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      isDocker: true
      MYSQL_HOST: db
      MYSQL_DATABASE: 'dsbd_customer'
      MYSQL_ROOT_PASSWORD: 'root'
      AUTH_URL: http://authentication:5002/authenticate
    networks:
      - default
    ports:
      - "5000:5000"    

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      isDocker: true
    networks:
      - default
    ports:
      - "5002:5002"

networks:
  default:
    name: dsbd_prj_default
    external: true
