# docker-compose.yml

version: '3'

services:

  db_customer:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dsbd_customer
    ports:
      - "3306:3306"

  db_category:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dsbd_category
    ports:
      - "3603:3603"
  
  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      isDocker: true
      MYSQL_HOST: db_customer
      MYSQL_DATABASE: 'dsbd_customer'
      MYSQL_ROOT_PASSWORD: 'root'
      AUTH_URL: http://authentication:5002/authenticate
    networks:
      - default
    ports:
      - "5000:5000"

  category:
    build:
      context: ./category
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      isDocker: true
      MYSQL_HOST: db_category
      MYSQL_DATABASE: 'dsbd_category'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PORT: 3603
      AUTH_URL: http://authentication:5002/verify_token
    networks:
      - default
    ports:
      - "8082:8082"

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      isDocker: true
    networks:
      - default
    ports:
      - "5002:5002"

networks:
  default:
    name: dsbd_prj_default
    external: true
