version: '3.8'
services:
  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      - isDocker=true
    networks:
      - dsbd_prj_default
    ports:
      - "5001:5001"
networks:
  dsbd_prj_default:
    external: true