version: '3'

services:
  category:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      - isDocker=true
      - MYSQL_DATABASE='dsbd_category'
      - MYSQL_USER='root'
      - MYSQL_ROOT_PASSWORD='root'
    networks:
      - dsbd_prj_default
    ports:
      - "8082:8082"
networks:
  dsbd_prj_default:
    external: true

