version: '3.8'
services:
  subscriber:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python subscriber.py'
    environment:
      - isDocker=true
    networks:
      - dsbd_prj_default
    ports:
      - 5000:5000
networks:
  dsbd_prj_default:
    external: true