version: '3'

services:
  authtentication:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    environment:
      - isDocker=true
    networks:
      - dsbd_prj_default
    ports:
      - "5002:5002"
networks:
  dsbd_prj_default:
    external: true

